# ['images'] other soon or not... :)
data_type: 'images'

data_path: "/Users/misha/Desktop/GitHub/Augment-X/Warp-D"


#-------------------------------------Image-------------------------------------------
classes_txt_path:

# True/False
flip_horizontal:
flip_vertical:

