data_path: "/Users/misha/Desktop/GitHub/Augment-X/Warp-D"

# classes_txt_path:

# example ['resize_image', 'crop_image']
# augmentations ['basic','flip_horizontal', 'flip_vertical', 'flip_both']
preprocessing: ['resize_image', 'crop_image', 'resize_image']
augmentations: ['basic','flip_horizontal', 'flip_vertical', 'flip_both']

# Change image size
save_proportions: False
w_img: 640
h_img: 640

#Crop_image (px)
crop_left: 100
crop_right: 100
crop_top: 0
crop_bottom: 200



