data_path: "/Users/misha/Desktop/GitHub/Augment-X/Warp-D"

classes_txt_path:

# example ['change_size', 'crop_image', 'change_size']
preprocessing: ['change_size']
augmentations: []

# Change image size
save_propoptions: True
w_img: 640
h_img: 640

#Crop_image (px)
crop_left: 20
crop_right: 20
crop_top: 30
crop_bottom: 

